apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: maarten-playground
  name: letsencrypt-prod
spec:
  acme:
    email: "maarten.vandeperre@redhat.com"
    http01: {}
    privateKeySecretRef:
      name: letsencrypt-prod
    server: "https://acme-v02.api.letsencrypt.org/directory"
    solvers:
      - http01:
          ingress:
            class: openshift-default